/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/abathur.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/abathur.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/anubarak.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/anubarak.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/arthas.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/arthas.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/azmodan.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/azmodan.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/brightwing.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/brightwing.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/chen.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/chen.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/diablo.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/diablo.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/etc.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/etc.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/falstad.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/falstad.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/gazlowe.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/gazlowe.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/illidan.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/illidan.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/jaina.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/jaina.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/kerrigan.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/kerrigan.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/lili.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/lili.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/malfurion.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/malfurion.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/muradin.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/muradin.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/murky.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/murky.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/nazeebo.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/nazeebo.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/nova.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/nova.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/raynor.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/raynor.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/rehgar.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/rehgar.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/sgt-hammer.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/sgt-hammer.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/sonya.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/sonya.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/stitches.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/stitches.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/sylvanas.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/sylvanas.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/tassadar.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/tassadar.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/the-lost-vikings.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/the-lost-vikings.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/thrall.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/thrall.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/tychus.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/tychus.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/tyrael.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/tyrael.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/tyrande.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/tyrande.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/uther.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/uther.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/valla.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/valla.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/zagara.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/zagara.webm"}' --intf=dummy --play-and-exit
/Applications/VLC.app/Contents/MacOS/VLC "/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos/zeratul.webm" --sout='#transcode{vcodec=VP80,vfilter=croppadd{cropleft=550,croptop=80,cropright=50,cropbottom=0}}:std{access=file,mux="ffmpeg{mux=webm}",dst="/Users/jnovack/Source/heroes-messageboard/public/assets/hero-videos-cropped/zeratul.webm"}' --intf=dummy --play-and-exit


/Applications/VLC.app/Contents/MacOS/VLC public/assets/hero-videos/kerrigan.webm --video-filter=croppadd --croppadd-croptop=150 --sout='std{access=file,mux="ffmpeg{mux=webm}",dst="~/Desktop/kerrigan.webm"}' --intf=dummy --play-and-exit